server:
  servlet:
    contextPath: /api/v1
spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: boradeexcursao
      host: localhost
      port: 27017

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
