server:
  servlet:
    contextPath: /api/v1
spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: boradeexcursao
      host: localhost
      port: 27017
      auto-index-creation: true
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

storage:
  agency:
    logo:
      path: /home/lenilson/Documents/storage/boradeexcursao/uploads/images/logos
  travel:
    image:
      path: /home/lenilson/Documents/storage/boradeexcursao/uploads/images/travels
